### PR TITLE
[WIP] Fixed Analog and added WeightSensor and MotorControl

### PR DESCRIPTION
**Pull request by MaybeRex**
Tested and built usage for phidgetAnalog and updated documentation

### CODE REVIEW

**Comment by RIAEvangelist** [comment]
Tested?

**Comment by MaybeRex** [comment]
Partially, MotorControl and WeightSensor need testing

**Comment by RIAEvangelist** [comment]
Let me know when it is ready

**Comment by MaybeRex** [comment]
MotorControl is ready and tested

**Comment by RIAEvangelist** [comment]
great how about weight sensor?

**Pull request merged**
